name: Build and Deploy Node.js + Next.js App to Azure Web App - QuickVerdictsDev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Install backend (root) dependencies
      - name: npm install (backend/root)
        run: npm install

      # Install and build frontend
      - name: npm install (frontend)
        run: |
          cd frontend
          npm install

      - name: Build Next.js (frontend)
        run: |
          cd frontend
          npm run build
          cd ..

      # If your backend also needs a build (e.g., TypeScript), add here:
      # - name: Build backend
      #   run: npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'QuickVerdictsDev'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2AAB04D0B6DF488D94F76E771AA27E8B }}

